<?php $_collection = $this->getCollection();	//	"getCollection()" method define in /app/code/local/Hs/Simplebanner/Block/Simplebanner.php file ?>
<div class="container">
	<div>
		<!-- Carousel
		================================================== -->
		<div id="myCarousel" class="carousel slide" data-ride="carousel">
			  <!-- Indicators -->
			  <!--<ol class="carousel-indicators">
				<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
				<li data-target="#myCarousel" data-slide-to="1"></li>
				<li data-target="#myCarousel" data-slide-to="2"></li>
				<li data-target="#myCarousel" data-slide-to="3"></li>
			  </ol>-->
				<div class="carousel-inner">
					<?php foreach($_collection AS $_banner){ ?>
						<div class="item <?php echo ($_count == 0) ? 'active' : '' ?>">
							<img src="<?php echo $this->getBaseUrl('').'media/'.$_banner->getImage(); ?>">     
						</div>
						<?php $_count++ ?>
					<?php } ?>          
				</div>
				<a class="left carousel-control" href="#myCarousel" data-slide="prev">
					<span class="glyphicon glyphicon-chevron-left"></span>
				</a>
				<a class="right carousel-control" href="#myCarousel" data-slide="next">
					<span class="glyphicon glyphicon-chevron-right"></span>
				</a>  
			<!-- /.carousel -->
				
		</div> 
		<div class="clearfix"></div>          
	</div>
</div>
<div class="clearfix"></div>

<script type="text/javascript">
		
		jQuery(document).ready(function(){
		  jQuery('.slider4').bxSlider({
			slideWidth: 288,
			minSlides: 2,
			maxSlides: 3,
			moveSlides: 1,
			slideMargin: 10,
			auto:true
		  });
		});
		
   </script>
